import type { Service } from '@/types/service'

export const services: Service[] = [
  {
    slug: 'web-engineering',
    serviceId: 'SERVICE_01',
    icon: 'code_blocks',
    title: 'Web Engineering',
    tagline: 'Arquitecturas frontend y backend de alto rendimiento, orientadas a velocidad, escalabilidad y conversión.',
    desc: 'Plataformas a medida orientadas a velocidad extrema, escalabilidad y conversiones implacables.',
    stack: ['Next.js', 'React', 'Node', 'TypeScript', 'Supabase'],
    duration: '3–8 semanas',
    delivery: 'Plataforma en producción + handoff',
    steps: [
      { title: 'Discovery', description: 'Definimos objetivos, métricas de éxito y arquitectura.' },
      { title: 'Build', description: 'Desarrollo iterativo con entregables semanales verificables.' },
      { title: 'Launch', description: 'Deploy, monitoreo y traspaso documentado.' },
    ],
    useCases: [
      'Startups que necesitan un MVP sólido y escalable.',
      'Negocios con un sitio lento que pierde conversiones.',
      'Equipos que necesitan una plataforma interna a medida.',
    ],
    ctaHeadline: 'Construyamos algo que aguante crecimiento real.',
    accent: false,
  },
  {
    slug: 'ux-ui-design',
    serviceId: 'SERVICE_02',
    icon: 'design_services',
    title: 'UX/UI System Design',
    tagline: 'Investigación, wireframing y sistemas de interfaz premium que fusionan estética industrial con usabilidad.',
    desc: 'Interfaces premium que fusionan estética industrial con usabilidad funcional para maximizar la retención.',
    stack: ['Figma', 'Design Systems', 'Prototyping', 'Tailwind'],
    duration: '2–5 semanas',
    delivery: 'Design system + prototipo navegable',
    steps: [
      { title: 'Research', description: 'Entendemos a tus usuarios y su contexto real.' },
      { title: 'Design', description: 'Wireframes, sistema visual y prototipo de alta fidelidad.' },
      { title: 'Handoff', description: 'Tokens, componentes y specs listos para desarrollo.' },
    ],
    useCases: [
      'Productos con mala retención por fricción de UX.',
      'Marcas que necesitan un sistema visual coherente.',
      'Equipos sin design system que quieren escalar.',
    ],
    ctaHeadline: 'Diseñemos una interfaz que la gente quiera usar.',
    accent: false,
  },
  {
    slug: 'app-architecture',
    serviceId: 'SERVICE_03',
    icon: 'smartphone',
    title: 'App Architecture',
    tagline: 'Sistemas móviles nativos y cross-platform iOS/Android construidos para durar.',
    desc: 'Sistemas móviles nativos y cross-platform iOS/Android construidos para durar.',
    stack: ['React Native', 'TypeScript', 'Supabase', 'Expo'],
    duration: '4–10 semanas',
    delivery: 'App publicable + backend',
    steps: [
      { title: 'Arquitectura', description: 'Definimos stack, datos y flujos offline-first.' },
      { title: 'Build', description: 'Desarrollo cross-platform con builds de prueba continuas.' },
      { title: 'Publish', description: 'Preparación y envío a las tiendas.' },
    ],
    useCases: [
      'Ideas que necesitan estar en iOS y Android sin duplicar equipo.',
      'Negocios que necesitan una app conectada a su operación.',
      'MVPs móviles que deben validar rápido.',
    ],
    ctaHeadline: 'Llevemos tu producto al bolsillo de tus usuarios.',
    accent: false,
  },
  {
    slug: 'auto-ops-crm',
    serviceId: 'SERVICE_04',
    icon: 'hub',
    title: 'Auto-Ops & CRM',
    tagline: 'Automatización end-to-end e integraciones con GoHighLevel. Operaciones que se ejecutan solas.',
    desc: 'Automatización end-to-end e integraciones con GoHighLevel. Operaciones que se ejecutan solas.',
    stack: ['GoHighLevel', 'Make.com', 'Webhooks', 'APIs', 'Zapier'],
    duration: '2–6 semanas',
    delivery: 'Automatizaciones + CRM configurado',
    steps: [
      { title: 'Auditoría', description: 'Mapeamos tus procesos manuales y cuellos de botella.' },
      { title: 'Automatización', description: 'Construimos flujos, pipelines y secuencias.' },
      { title: 'Optimización', description: 'Medimos, ajustamos y documentamos.' },
    ],
    useCases: [
      'Agencias que pierden tiempo en tareas repetitivas.',
      'Equipos de ventas sin seguimiento automatizado.',
      'Negocios que quieren operar con menos fricción humana.',
    ],
    ctaHeadline: 'Automaticemos lo que hoy te quita horas cada día.',
    accent: true,
  },
  {
    slug: 'consulting',
    serviceId: 'SERVICE_05',
    icon: 'school',
    title: 'Consultoría & Capacitación',
    tagline: 'Estrategia, mentoría y formación para equipos que quieren operar con AI desde adentro.',
    desc: 'Estrategia, mentoría y formación para equipos que quieren operar con AI desde adentro.',
    stack: ['Estrategia', 'AI', 'Workshops', 'Mentoría'],
    duration: 'Por sesión o retainer',
    delivery: 'Workshops + roadmap accionable',
    steps: [
      { title: 'Diagnóstico', description: 'Evaluamos dónde la AI puede mover la aguja en tu operación.' },
      { title: 'Formación', description: 'Workshops prácticos con tu equipo, no teoría.' },
      { title: 'Roadmap', description: 'Plan de adopción medible y por fases.' },
    ],
    useCases: [
      'Equipos que quieren adoptar AI sin saber por dónde empezar.',
      'Fundadores que necesitan una estrategia técnica clara.',
      'Empresas que quieren capacitar a su equipo interno.',
    ],
    ctaHeadline: 'Preparemos a tu equipo para operar con AI de verdad.',
    accent: false,
  },
]
